### ISSUE TITLE
GTA-Lucky-Wheel

### ISSUE THREAD

**Issue by pwnmactep** [gyfen/GTA-Lucky-Wheel#1]
Hi,

i  checkout out your https://github.com/gyfen/GTA-Lucky-Wheel script...
seems the delay isnt right.. do you figure out an better amount to delay ?

i try :500,4000 unlucky..

Hope for answer , btw. ty for shareing

**Comment by gyfen** [comment]
Hi pwnmactep,

It's very possible that the delay isn't accurate. As I said, this script is inconsistent and you probably won't get it in one spin. But for me it's better than randomly spinning. Many people have claimed to have found a perfect time, but no one has proven it's actually possible to win it every time with a specific timing. Therefore my script is just a tool to automate the timing for you.

I hope this helps

- Gyfen
