### ISSUE TITLE
Dosent work at all!

### ISSUE THREAD

**Issue by Fischchen** [gyfen/GTA-Lucky-Wheel#2]
When i try to run the script it seens to press enter but after that nothing happens. No spinning no tooltip nothing. I have my game on 1920x1080p

**Comment by dirtyharryiv** [comment]
You need to check the Pixel Positions in the Script!

**Comment by Fischchen** [comment]
I dont know how... Can somebody just pleas give me your settings, that might work on my System?

Thanks in advance

**Comment by JensBue** [comment]
Assuming by your Username you are from Germany.
Try editing the following line in the .ahk file like this:

PixelGetColor, color, 135, 30, RGB

and then try again.

**Comment by AAbrains** [comment]
hey guys help me ...when i press f1 it just press enter and hold the wheel...but it dosent spin it ...i dont know anything about pixel position so plzz help
