### ISSUE TITLE
Looping forever

### ISSUE THREAD

**Issue by danielmouraa** [gyfen/GTA-Lucky-Wheel#7]
When the script get into the loop to wait the delay, it gets stuck into "waiting ms..." but it dosent wait

**Comment by User54a** [comment]
Hi @danielmouraa,

Thank you for submitting this issue.

I had the same problem and moving delay variable declaration a bit higher helped with it. Gyfen haven't merged the Pull Request yet, but you can get the code [here](https://github.com/gyfen/GTA-Lucky-Wheel/blob/d9bbffe25ceb7d8fcc529fe64d016f63a03a4c4f/Lucky%20Wheel.ahk). Just copy and paste it into the script you have on your PC.

If the issue will still reproduce, I would like to help you to debug it :)

**Comment by danielmouraa** [comment]
Thank you!! It worked!

I had to adjust the delay to 2691

Youre awesome

**Comment by User54a** [comment]
Happy to help! :)

I guess @gyfen will close this issue once the [pull request](https://github.com/gyfen/GTA-Lucky-Wheel/pull/6) is merged.

**Comment by gyfen** [comment]
Hi! Sorry, I didn't get any notifications.
I haven't checked, but I'm trusting @User54a

**Comment by User54a** [comment]
Hi @gyfen, you should press this button to be notified on any activity in the repository: 
![image](https://user-images.githubusercontent.com/63922776/102488382-04c45f00-407d-11eb-9f41-8efbdbf22ff6.png)
