### ISSUE TITLE
It spins immediately.

### ISSUE THREAD

**Issue by Wolffy821** [gyfen/GTA-Lucky-Wheel#8]
Hi. I issue a problem when the .ahk detected the Wheel Spin dialogue and it spins immediately. It just shows "waiting ms..." then spin. Can you help? Thanks <3

**Comment by User54a** [comment]
Hi, @Wolffy821  

I guess you solved the issue by yourself. Did you use my [suggestion](https://github.com/gyfen/GTA-Lucky-Wheel/issues/7#issuecomment-742710389)?
